name: Node.js Package

on:
  push:
    branches:
      - main

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: '@pulbyte'
      - name: List specific environment variables
        run: |
          echo "NODE_AUTH_TOKEN is set: $(if [ -n "$NODE_AUTH_TOKEN" ]; then echo 'YES'; else echo 'NO'; fi)"
        continue-on-error: true
      - run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm publish