name: Node.js Package

on:
  push:
    branches:
      - main

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: '@pulbyte'
      - name: List specific environment variables
        run: |
          echo "NODE_AUTH_TOKEN is set: $(if [ -n "$NODE_AUTH_TOKEN" ]; then echo 'YES'; else echo 'NO'; fi)"
        continue-on-error: true
      - name: Create .npmrc file  
        run: |
          echo "@pulbyte:registry=https://npm.pkg.github.com/" > ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc
      - name: Display .npmrc content
        run: cat ~/.npmrc
        continue-on-error: true
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}