name: Node.js Package

on:
  push:
    branches:
      - main

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: '@pulbyte'
      - name: List specific environment variables
        run: |
          echo "NODE_AUTH_TOKEN: $NODE_AUTH_TOKEN"
          echo "NPM_TOKEN: $NPM_TOKEN"
        continue-on-error: true
      - name: Log .npmrc file
        run: cat $NPM_CONFIG_USERCONFIG
        continue-on-error: true
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}